/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.barkbites.StaffForms;

import com.mycompany.barkbites.FormNavigator;
import com.mycompany.barkbites.data.staff.StaffFirebaseBootstrap;
import com.mycompany.barkbites.data.staff.StaffStatisticsService;
import com.mycompany.barkbites.data.staff.StaffStatisticsSummary;
import java.awt.Color;
import java.awt.Font;
import java.util.concurrent.ExecutionException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author markd
 */
public class StaffStatistics extends javax.swing.JFrame {

    private final StaffStatisticsService statisticsService = new StaffStatisticsService();
    private JLabel titleLabel;
    private JLabel totalOrdersLabel;
    private JLabel totalOrdersValue;
    private JLabel totalSalesLabel;
    private JLabel totalSalesValue;
    private JLabel monthOrdersLabel;
    private JLabel monthOrdersValue;
    private JLabel monthSalesLabel;
    private JLabel monthSalesValue;
    private JLabel statusLabel;
    private javax.swing.JButton refreshButton;

    /**
     * Creates new form StaffStatistics
     */
    public StaffStatistics() {
        initComponents();

        getContentPane().setComponentZOrder(BG, getContentPane().getComponentCount() - 1);

        makeButtonInvisible(OrdersButton);
        makeButtonInvisible(InventoryButton);
        makeButtonInvisible(MenuButton);
        makeButtonInvisible(LogoutButton);

        OrdersButton.addActionListener(evt -> openStaffOrders());
        InventoryButton.addActionListener(evt -> openStaffInventory());
        MenuButton.addActionListener(evt -> openStaffMenu());
        LogoutButton.addActionListener(evt -> openStaffLandingPage());

        StaffFirebaseBootstrap.ensureInitialized(this);
        configureUi();
        loadSummaryAsync();

        this.setResizable(false);
    }

    private void configureUi() {
        titleLabel.setFont(new Font("Arial", Font.BOLD, 22));
        titleLabel.setForeground(Color.WHITE);
        statusLabel.setForeground(Color.WHITE);

        refreshButton.addActionListener(evt -> loadSummaryAsync());
    }

    private void loadSummaryAsync() {
        setBusy(true);
        javax.swing.SwingWorker<StaffStatisticsSummary, Void> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected StaffStatisticsSummary doInBackground() {
                return statisticsService.loadSummary();
            }

            @Override
            protected void done() {
                try {
                    StaffStatisticsSummary summary = get();
                    totalOrdersValue.setText(Integer.toString(summary.totalOrders()));
                    totalSalesValue.setText(formatPesos(summary.totalSalesCents()));
                    monthOrdersValue.setText(Integer.toString(summary.monthOrders()));
                    monthSalesValue.setText(formatPesos(summary.monthSalesCents()));
                    statusLabel.setText("Loaded current sales summary.");
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                    statusLabel.setText("Statistics load interrupted.");
                } catch (ExecutionException ee) {
                    String message = ee.getCause() != null ? ee.getCause().getMessage() : ee.getMessage();
                    statusLabel.setText("Statistics load failed.");
                    JOptionPane.showMessageDialog(StaffStatistics.this, message, "Statistics load failed", JOptionPane.ERROR_MESSAGE);
                } finally {
                    setBusy(false);
                }
            }
        };
        worker.execute();
    }

    private void setBusy(boolean busy) {
        refreshButton.setEnabled(!busy);
    }

    private static String formatPesos(long cents) {
        return String.format(java.util.Locale.US, "₱%,.2f", cents / 100.0);
    }

    private void openStaffOrders() {
        FormNavigator.redirect(this, new StaffOrders());
    }

    private void openStaffInventory() {
        FormNavigator.redirect(this, new StaffInventory());
    }

    private void openStaffMenu() {
        FormNavigator.redirect(this, new StaffMenu());
    }

    private void openStaffLandingPage() {
        FormNavigator.redirect(this, new StaffLandingPage());
    }

    private static void makeButtonInvisible(javax.swing.JButton button) {
        button.setText("");
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        totalOrdersValue = new javax.swing.JLabel();
        totalSalesValue = new javax.swing.JLabel();
        monthOrdersValue = new javax.swing.JLabel();
        monthSalesValue = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        OrdersButton = new javax.swing.JButton();
        InventoryButton = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalOrdersValue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalOrdersValue.setText("0");
        getContentPane().add(totalOrdersValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 130, 30));

        totalSalesValue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalSalesValue.setText("₱0.00");
        getContentPane().add(totalSalesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 220, 30));

        monthOrdersValue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        monthOrdersValue.setText("0");
        getContentPane().add(monthOrdersValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 170, 30));

        monthSalesValue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        monthSalesValue.setText("₱0.00");
        getContentPane().add(monthSalesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 150, 30));

        refreshButton.setText("Refresh");
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 120, 50));

        OrdersButton.setText("jButton1");
        getContentPane().add(OrdersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 70));

        InventoryButton.setText("jButton2");
        getContentPane().add(InventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 70));

        MenuButton.setText("jButton3");
        getContentPane().add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 70));

        LogoutButton.setText("jButton4");
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 90, 40));

        HistoryButton.setText("jButton6");
        getContentPane().add(HistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 140, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/barkbites/StaffDesign/StaffStatistics.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton HistoryButton;
    private javax.swing.JButton InventoryButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton OrdersButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel monthOrdersValue;
    private javax.swing.JLabel monthSalesValue;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel totalOrdersValue;
    private javax.swing.JLabel totalSalesValue;
    // End of variables declaration//GEN-END:variables
}
