/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.barkbites.StaffForms;

import com.mycompany.barkbites.FormNavigator;

/**
 * OOP used here:
 * Encapsulation keeps the navigation helpers private to this form.
 * Abstraction hides the screen-switching details behind button clicks.
 * Inheritance comes from extending JFrame.
 * Polymorphism shows up in the event listeners reacting to runtime clicks.
 *
 * @author markd
 */
public class StaffHistory extends javax.swing.JFrame {

    /**
     * Creates new form StaffHistory
     */
    public StaffHistory() {
        initComponents();
        // Action: keep the generated buttons clickable while hiding their chrome.
        makeButtonInvisible(StaffOrders);
        makeButtonInvisible(StaffInventory);
        makeButtonInvisible(StaffMenu);
        makeButtonInvisible(StaffStatistics);
        makeButtonInvisible(Refresh);
        makeButtonInvisible(Logout);

        // Action: connect each button to its matching screen.
        StaffOrders.addActionListener(evt -> openStaffOrders());
        StaffInventory.addActionListener(evt -> openStaffInventory());
        StaffMenu.addActionListener(evt -> openStaffMenu());
        StaffStatistics.addActionListener(evt -> openStaffStatistics());
        Logout.addActionListener(evt -> openStaffLandingPage());
        Refresh.addActionListener(evt -> refreshPage());
    }

    private static void makeButtonInvisible(javax.swing.JButton button) {
        // Keeps the hit area active while removing the visible button styling.
        button.setText("");
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
    }

    private void openStaffOrders() {
        // Action: open the Orders screen.
        FormNavigator.redirect(this, new StaffOrders());
    }

    private void openStaffInventory() {
        // Action: open the Inventory screen.
        FormNavigator.redirect(this, new StaffInventory());
    }

    private void openStaffMenu() {
        // Action: open the Menu screen.
        FormNavigator.redirect(this, new StaffMenu());
    }

    private void openStaffStatistics() {
        // Action: open the Statistics screen.
        FormNavigator.redirect(this, new StaffStatistics());
    }

    private void openStaffLandingPage() {
        // Action: return to the landing page.
        FormNavigator.redirect(this, new StaffLandingPage());
    }

    private void refreshPage() {
        // Action: reload the current history screen.
        FormNavigator.redirect(this, new StaffHistory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffOrders = new javax.swing.JButton();
        StaffInventory = new javax.swing.JButton();
        StaffMenu = new javax.swing.JButton();
        StaffStatistics = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffOrders.setText("jButton1");
        getContentPane().add(StaffOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 70));

        StaffInventory.setText("jButton2");
        getContentPane().add(StaffInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 70));

        StaffMenu.setText("jButton3");
        getContentPane().add(StaffMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 70));

        StaffStatistics.setText("jButton4");
        getContentPane().add(StaffStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 140, 70));

        Refresh.setText("jButton5");
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 100, 50));

        Logout.setText("jButton6");
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\markd\\Downloads\\Staff Design\\StaffHistory.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton StaffInventory;
    private javax.swing.JButton StaffMenu;
    private javax.swing.JButton StaffOrders;
    private javax.swing.JButton StaffStatistics;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
